---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wdrmopki/demolingo.dobre-paloti.ro
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
